[parameter]
[parameter.tensor]
D  = 4     # tensor_dim
CHI  = 16  # env_dim

[parameter.simple_update]
tau = 0.01
num_step= 1000

[parameter.full_update]
tau = 0.01
num_step = 1

[parameter.ctm]
iteration_max = 5

[lattice]
type = "square lattice"
L_sub = [2,2]

[model]
type = "spin"
S = 1.0
Jx = 1.0
Jy = 1.0
Jz = 1.0

