[parameter]
[parameter.simple_update]
tau = 0.01
num_step = 1000

[parameter.full_update]
tau = 0.01
num_step = 1

[parameter.ctm]
iteration_max = 5
dimension = 16

[lattice]
type = "square lattice"
L = 2
W = 2
initial = "antiferro"
virtual_dim = 4

[model]
type = "spin"
J = 1.0
