[parameter]
D  = 4     # tensor_dim
CHI  = 16  # env_dim

tau_simple =  0.01
num_simple_step = 1000
tau_full = 0.01
num_full_step = 1
Random_amp = 0.02
second_ST = true
Read_Initial = false
ctm_iteration_max = 2

[lattice]
L = [2,2]

[[hamiltonian]]
id = 0
value = """
 -0.25   0.175  0.175   0.0
  0.175  0.25   0.0     0.175
  0.175  0.0    0.25    0.175
  0.0    0.175  0.175  -0.25
"""

[bond]
simple_update = """
0 1 h 0
3 2 h 0
2 3 h 0
1 0 h 0
0 2 v 0
3 1 v 0
2 0 v 0
1 3 v 0
"""

full_update = """
0 1 h 0
3 2 h 0
2 3 h 0
1 0 h 0
0 2 v 0
3 1 v 0
2 0 v 0
1 3 v 0
"""
