[parameter]
[parameter.tensor]
D  = 2     # tensor_dim
CHI  = 10  # env_dim

[parameter.simple_update]
num_step = 10000
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[parameter.ctm]
iteration_max = 10

[lattice]
type = "square lattice"
L_sub = [2,2]

[model]
type = "spin"
Jz = -1.0
Jx = 0.0
Jy = 0.0
G = 1.4

